# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: AppBundle:UserEntity

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                success_handler: authentication_handler
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - eve_sso_authenticator
            provider: db_provider

    access_control:
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/sso, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/admin/contracts, roles: ROLE_TRANSACTION_ADMIN }
        - {path: ^/admin, roles: ROLE_ADMIN }
        - {path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_REMEMBERED] }

    role_hierarchy:
        ROLE_SYSTEM_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_TRANSACTION_ADMIN
        ROLE_TRANSACTION_ADMIN: ROLE_MEMBER
        ROLE_MEMBER: ROLE_USER
        ROLE_ALLY: ROLE_USER
        ROLE_FRIEND: ROLE_USER
        ROLE_GUEST: ROLE_USER
        ROLE_OTHER1: ROLE_USER
        ROLE_OTHER2: ROLE_USER
        ROLE_OTHER3: ROLE_USER

    encoders:
        AppBundle\Entity\UserEntity:
            algorithm: bcrypt